-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-02 16:09:22 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE albumgenre (
    id_album  INTEGER NOT NULL,
    genre     VARCHAR2(30) NOT NULL
);

ALTER TABLE albumgenre ADD CONSTRAINT albumgenre_pk PRIMARY KEY ( id_album,
                                                                  genre );

CREATE TABLE albuminfo (
    id_album  INTEGER NOT NULL,
    artist    VARCHAR2(70) NOT NULL,
    album     VARCHAR2(75) NOT NULL,
    year      INTEGER NOT NULL
);

ALTER TABLE albuminfo ADD CONSTRAINT albuminfo_pk PRIMARY KEY ( id_album );

CREATE TABLE artists (
    artist VARCHAR2(70) NOT NULL
);

ALTER TABLE artists ADD CONSTRAINT artists_pk PRIMARY KEY ( artist );

CREATE TABLE genres (
    genre VARCHAR2(30) NOT NULL
);

ALTER TABLE genres ADD CONSTRAINT genres_pk PRIMARY KEY ( genre );

ALTER TABLE albumgenre
    ADD CONSTRAINT albumgenre_albuminfo_fk FOREIGN KEY ( id_album )
        REFERENCES albuminfo ( id_album );

ALTER TABLE albumgenre
    ADD CONSTRAINT albumgenre_genres_fk FOREIGN KEY ( genre )
        REFERENCES genres ( genre );

ALTER TABLE albuminfo
    ADD CONSTRAINT albuminfo_artists_fk FOREIGN KEY ( artist )
        REFERENCES artists ( artist );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
